import type {
  AgentItem,
  ArchitectureItem,
  CaseItem,
  DeliveryItem,
  DiagnosisItem,
  KpiCard,
  LibraryAsset,
  NavigationKey,
  ProductionItem,
  TimelineEvent,
  ValidationItem,
} from './types'

export const navigation: { key: NavigationKey; label: string }[] = [
  { key: 'resumen', label: 'Resumen' },
  { key: 'casos', label: 'Casos' },
  { key: 'diagnostico', label: 'Diagnóstico' },
  { key: 'arquitectura', label: 'Arquitectura' },
  { key: 'produccion', label: 'Producción' },
  { key: 'validacion', label: 'Validación' },
  { key: 'entrega', label: 'Demo / Entrega' },
  { key: 'biblioteca', label: 'Biblioteca' },
  { key: 'agentes', label: 'Agentes' },
]

export const kpis: KpiCard[] = [
  { label: 'Casos activos', value: '12', delta: '3 entraron esta semana', tone: 'positive' },
  { label: 'Casos bloqueados', value: '2', delta: 'Requieren decisión', tone: 'warning' },
  { label: 'Demos en preparación', value: '4', delta: '2 esta semana', tone: 'neutral' },
  { label: 'Agentes internos activos', value: '10', delta: 'Motor v1 definido', tone: 'neutral' },
]

export const cases: CaseItem[] = [
  {
    id: 'CASE-001',
    company: 'Maison Derma',
    vertical: 'Estética',
    projectType: 'Agente de recepción + demo',
    currentPhase: 'Diagnóstico',
    currentAgent: 'Agente de Diagnóstico',
    nextAgent: 'Arquitectura de Solución',
    priority: 'Alta',
    status: 'Activo',
    expectedOutput: 'Informe de diagnóstico',
    blocker: 'Sin bloqueo',
    targetDate: 'Lun 10:00',
    origin: 'Lead validado desde la web AGENTSYST',
    need: 'Mejorar recepción y cualificación inicial',
    diagnosisSummary: 'Hay oportunidad de implantar un agente de atención sectorial con demo rápida.',
    strategyNote: 'Caso ideal para demostrar velocidad, especialización y entrega modular.',
    activeWorkstreams: ['Diagnóstico', 'Diseño demo'],
    dependencies: ['Cierre del informe de diagnóstico', 'Definir vertical exacta'],
    devSupport: 'No todavía',
    deliveryType: 'Demo funcional',
    deliveryStatus: 'En preparación',
    missingItems: ['Informe final', 'Ruta de demo', 'Aprobación interna'],
    history: [
      { label: 'Lead aceptado dentro del motor', time: 'Hoy 08:30', tone: 'success' },
      { label: 'Caso asignado a Diagnóstico', time: 'Hoy 08:45', tone: 'info' },
      { label: 'Pendiente de cierre del informe', time: 'Hoy 09:20', tone: 'warning' },
    ],
    checklist: [
      { label: 'Lead aceptado', done: true },
      { label: 'Diagnóstico creado', done: false },
      { label: 'Arquitectura definida', done: false },
      { label: 'Demo preparada', done: false },
    ],
  },
  {
    id: 'CASE-002',
    company: 'Smile Atelier',
    vertical: 'Clínica dental',
    projectType: 'Landing + agente conversacional',
    currentPhase: 'Arquitectura',
    currentAgent: 'Arquitectura de Solución',
    nextAgent: 'Diseño de Solución',
    priority: 'Alta',
    status: 'Activo',
    expectedOutput: 'Documento de arquitectura',
    blocker: 'Esperando validación de oferta',
    targetDate: 'Lun 13:00',
    origin: 'Lead derivado desde captación comercial',
    need: 'Crear sistema de captación y atención inicial para clínica dental',
    diagnosisSummary: 'El caso necesita una estructura combinada de landing + agente sectorial.',
    strategyNote: 'La vertical dental exige mensajes más sensibles y validación cuidadosa.',
    activeWorkstreams: ['Arquitectura', 'Preparación landing'],
    dependencies: ['Validación de oferta', 'Selección de canal principal'],
    devSupport: 'Sí, en fase técnica posterior',
    deliveryType: 'Propuesta + demo conversacional',
    deliveryStatus: 'Arquitectura en cierre',
    missingItems: ['Validación comercial', 'Mapa de canales'],
    history: [
      { label: 'Diagnóstico completado', time: 'Ayer 17:20', tone: 'success' },
      { label: 'Caso pasa a Arquitectura', time: 'Hoy 08:10', tone: 'info' },
      { label: 'Bloqueo comercial detectado', time: 'Hoy 09:05', tone: 'warning' },
    ],
    checklist: [
      { label: 'Lead aceptado', done: true },
      { label: 'Diagnóstico creado', done: true },
      { label: 'Arquitectura definida', done: false },
      { label: 'Demo preparada', done: false },
    ],
  },
  {
    id: 'CASE-003',
    company: 'Core AGENTSYST',
    vertical: 'Interno',
    projectType: 'Panel interno del motor',
    currentPhase: 'Producción',
    currentAgent: 'Producción Técnica',
    nextAgent: 'QA y Validación',
    priority: 'Alta',
    status: 'Activo',
    expectedOutput: 'V1 operativa del panel',
    blocker: 'Definir fichas de detalle',
    targetDate: 'Lun 09:00',
    origin: 'Necesidad interna estratégica',
    need: 'Tener el motor AGENTSYST visible y operable desde un panel independiente',
    diagnosisSummary: 'El panel debe reflejar casos, agentes, fases, outputs y entrega.',
    strategyNote: 'Este caso es la infraestructura operativa que ordena el resto del sistema.',
    activeWorkstreams: ['Producción técnica', 'UX operativa', 'Modelado de fichas'],
    dependencies: ['Cierre de estructura de detalle', 'Pulido visual final'],
    devSupport: 'Sí, directo',
    deliveryType: 'Panel interno V1',
    deliveryStatus: 'En construcción',
    missingItems: ['Checklist avanzada', 'Pulido demo-ready'],
    history: [
      { label: 'Estructura del motor definida', time: 'Hoy 09:10', tone: 'success' },
      { label: 'UI base del panel actualizada', time: 'Hoy 09:35', tone: 'success' },
      { label: 'Pendiente acabado de detalle', time: 'Hoy 10:00', tone: 'warning' },
    ],
    checklist: [
      { label: 'Estructura del motor definida', done: true },
      { label: 'Panel base actualizado', done: true },
      { label: 'Fichas operativas listas', done: false },
      { label: 'Demo-ready para lunes', done: false },
    ],
  },
]

export const diagnosisQueue: DiagnosisItem[] = [
  {
    caseId: 'CASE-001',
    company: 'Maison Derma',
    diagnosisAgent: 'Agente de Diagnóstico',
    detectedProblem: 'Recepción lenta y no estandarizada',
    opportunity: 'Agente de atención sectorial + demo rápida',
    complexity: 'Media',
    reportStatus: 'En curso',
    nextDecision: 'Pasar a arquitectura',
  },
  {
    caseId: 'CASE-004',
    company: 'Aura Studio',
    diagnosisAgent: 'Agente de Diagnóstico',
    detectedProblem: 'Captación sin cualificación',
    opportunity: 'Landing + cualificación automatizada',
    complexity: 'Media',
    reportStatus: 'Pendiente de cierre',
    nextDecision: 'Validar alcance',
  },
]

export const architectureQueue: ArchitectureItem[] = [
  {
    caseId: 'CASE-002',
    company: 'Smile Atelier',
    solutionType: 'Landing + agente conversacional',
    channels: 'Web · WhatsApp',
    requiredAgents: 'Landing · Conversacional · Sectorial',
    mandatoryOutputs: 'Arquitectura · Copy base · Brief agente',
    architectureStatus: 'En definición',
    nextStep: 'Diseño de solución',
  },
  {
    caseId: 'CASE-005',
    company: 'Nova Habitat',
    solutionType: 'Agente comercial inmobiliario',
    channels: 'WhatsApp · Telegram',
    requiredAgents: 'Conversacional · Sectorial · Técnico',
    mandatoryOutputs: 'Arquitectura · Flujos · Demo',
    architectureStatus: 'Lista para revisión',
    nextStep: 'Validación interna',
  },
]

export const productionQueue: ProductionItem[] = [
  {
    caseId: 'CASE-003',
    company: 'Core AGENTSYST',
    workstream: 'Panel / dashboard',
    ownerAgent: 'Producción Técnica',
    expectedOutput: 'Panel interno V1',
    status: 'En curso',
    blocker: 'Fichas aún no modeladas',
    dependency: 'Brief técnico v2',
    deadline: 'Lun 09:00',
  },
  {
    caseId: 'CASE-002',
    company: 'Smile Atelier',
    workstream: 'Landing',
    ownerAgent: 'Diseñador de Landing',
    expectedOutput: 'Estructura + copy base',
    status: 'Pendiente',
    blocker: 'Esperando arquitectura final',
    dependency: 'Arquitectura',
    deadline: 'Mar 11:00',
  },
]

export const validationQueue: ValidationItem[] = [
  {
    caseId: 'CASE-005',
    company: 'Nova Habitat',
    asset: 'Arquitectura del agente comercial',
    reviewer: 'QA y Validación',
    qaStatus: 'En revisión',
    issue: 'Falta aclarar escalado a humano',
    requiredAction: 'Corregir flujo de objeciones',
  },
  {
    caseId: 'CASE-006',
    company: 'Dermacare Hub',
    asset: 'Landing demo',
    reviewer: 'QA y Validación',
    qaStatus: 'Bloqueada',
    issue: 'Copy no adaptado al sector',
    requiredAction: 'Pasar por especialización sectorial',
  },
]

export const deliveryQueue: DeliveryItem[] = [
  {
    caseId: 'CASE-007',
    company: 'Clinique Nova',
    deliveryType: 'Demo funcional',
    demoStatus: 'Casi lista',
    missingItems: 'Checklist final + assets',
    owner: 'Preparación de Demo / Entrega',
    targetDate: 'Lun 16:00',
    readiness: [
      { label: 'Assets organizados', status: 'OK' },
      { label: 'QA final', status: 'Pendiente' },
      { label: 'Narrativa demo', status: 'En curso' },
    ],
  },
  {
    caseId: 'CASE-008',
    company: 'Studio Aura',
    deliveryType: 'Propuesta + demo conversacional',
    demoStatus: 'Bloqueada',
    missingItems: 'Definir tono sectorial',
    owner: 'Vera',
    targetDate: 'Mar 12:00',
    readiness: [
      { label: 'Arquitectura', status: 'OK' },
      { label: 'Especialización sectorial', status: 'Bloqueada' },
      { label: 'Checklist final', status: 'Pendiente' },
    ],
  },
]

export const agents: AgentItem[] = [
  {
    id: 'AG-001',
    name: 'Intake de Lead',
    mission: 'Crear caso operativo desde lead validado',
    phase: 'Intake',
    input: 'Lead validado',
    output: 'Ficha de caso',
    status: 'Disponible',
    handoffTo: 'Diagnóstico',
  },
  {
    id: 'AG-002',
    name: 'Diagnóstico',
    mission: 'Analizar necesidad y producir informe',
    phase: 'Diagnóstico',
    input: 'Ficha de caso',
    output: 'Informe de diagnóstico',
    status: 'Ejecutando',
    handoffTo: 'Arquitectura de Solución',
  },
  {
    id: 'AG-003',
    name: 'Arquitectura de Solución',
    mission: 'Definir sistema, agentes y outputs',
    phase: 'Arquitectura',
    input: 'Informe de diagnóstico',
    output: 'Documento de arquitectura',
    status: 'Ejecutando',
    handoffTo: 'Diseño de Solución',
  },
  {
    id: 'AG-004',
    name: 'Diseño de Solución',
    mission: 'Activar ramas de producción',
    phase: 'Diseño',
    input: 'Documento de arquitectura',
    output: 'Plan de solución',
    status: 'Disponible',
    handoffTo: 'Agentes especializados',
  },
  {
    id: 'AG-005',
    name: 'Diseñador de Landing',
    mission: 'Construir landing o interfaz comercial',
    phase: 'Producción',
    input: 'Plan de solución',
    output: 'Estructura y copy base',
    status: 'Esperando input',
    handoffTo: 'Producción Técnica',
  },
  {
    id: 'AG-006',
    name: 'Sistema Conversacional',
    mission: 'Diseñar el agente conversacional del cliente',
    phase: 'Producción',
    input: 'Arquitectura y contexto sectorial',
    output: 'Brief del agente',
    status: 'Disponible',
    handoffTo: 'Especialización Sectorial',
  },
  {
    id: 'AG-007',
    name: 'Especialización Sectorial',
    mission: 'Adaptar el agente al gremio concreto',
    phase: 'Producción',
    input: 'Brief del agente',
    output: 'Instrucciones sectoriales',
    status: 'Disponible',
    handoffTo: 'Producción Técnica',
  },
  {
    id: 'AG-008',
    name: 'Producción Técnica',
    mission: 'Construir piezas técnicas y coordinar con Dev',
    phase: 'Producción',
    input: 'Plan y assets',
    output: 'Componentes listos',
    status: 'Ejecutando',
    handoffTo: 'QA y Validación',
  },
  {
    id: 'AG-009',
    name: 'QA y Validación',
    mission: 'Revisar coherencia, calidad y faltantes',
    phase: 'Validación',
    input: 'Outputs de producción',
    output: 'Informe QA',
    status: 'En revisión',
    handoffTo: 'Preparación de Demo / Entrega',
  },
  {
    id: 'AG-010',
    name: 'Preparación de Demo / Entrega',
    mission: 'Empaquetar demo o entrega final',
    phase: 'Demo / Entrega',
    input: 'Outputs aprobados',
    output: 'Paquete final',
    status: 'Disponible',
    handoffTo: 'Vera',
  },
]

export const libraryAssets: LibraryAsset[] = [
  {
    id: 'LIB-001',
    title: 'Arquitectura maestra del negocio',
    type: 'Arquitectura',
    domain: 'Core',
    usage: 'Base de diseño del sistema',
    updatedAt: 'Ayer',
    owner: 'Val',
  },
  {
    id: 'LIB-002',
    title: 'Plantilla landing estética',
    type: 'Plantilla',
    domain: 'Beauty',
    usage: 'Casos de captación estética',
    updatedAt: 'Ayer',
    owner: 'AGENTSYST',
  },
  {
    id: 'LIB-003',
    title: 'Playbook agente diagnóstico',
    type: 'Playbook',
    domain: 'Operación',
    usage: 'Informes de diagnóstico',
    updatedAt: 'Hoy',
    owner: 'Vera',
  },
  {
    id: 'LIB-004',
    title: 'Prompt base agente recepción',
    type: 'Prompt',
    domain: 'Conversacional',
    usage: 'Adaptación por vertical',
    updatedAt: 'Hoy',
    owner: 'AGENTSYST',
  },
]

export const timeline: TimelineEvent[] = [
  {
    id: 'T-001',
    title: 'Motor interno v1 definido',
    description: 'Queda cerrada la estructura base por agentes, fases y handoffs.',
    time: 'Hace 5 min',
    tone: 'success',
  },
  {
    id: 'T-002',
    title: 'CASE-003 pasa a producción',
    description: 'El panel interno entra en tramo técnico para quedar operativo el lunes.',
    time: 'Hace 12 min',
    tone: 'info',
  },
  {
    id: 'T-003',
    title: 'Bloqueo detectado en fichas de detalle',
    description: 'Falta modelar las fichas por caso, agente y entrega.',
    time: 'Hace 27 min',
    tone: 'warning',
  },
]
